(function exposeGeoSphereContent(globalScope) {
  const allowedCountryNames = new Set([
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia",
    "DR Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Republic of the Congo",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
    "Antarctica",
    "Greenland",
    "Kosovo",
    "Western Sahara",
  ]);

  const triviaExtras = {
    landmarks: [
      ["France", "Eiffel Tower"],
      ["India", "Taj Mahal"],
      ["China", "Great Wall"],
      ["Italy", "Colosseum"],
      ["Brazil", "Christ the Redeemer"],
      ["Egypt", "Pyramids of Giza"],
      ["Peru", "Machu Picchu"],
      ["Jordan", "Petra"],
      ["Cambodia", "Angkor Wat"],
      ["Greece", "Parthenon"],
      ["United Kingdom", "Stonehenge"],
      ["United States", "Statue of Liberty"],
    ],
    dishes: [
      ["Japan", "sushi"],
      ["Italy", "pizza"],
      ["Mexico", "tacos"],
      ["Spain", "paella"],
      ["Thailand", "pad thai"],
      ["Vietnam", "pho"],
      ["India", "biryani"],
      ["Brazil", "feijoada"],
      ["Turkey", "kebab"],
      ["Morocco", "tagine"],
      ["South Korea", "kimchi"],
      ["Indonesia", "nasi goreng"],
    ],
    cities: [
      ["Turkey", "Istanbul"],
      ["Australia", "Sydney"],
      ["United States", "New York City"],
      ["Brazil", "Rio de Janeiro"],
      ["United Arab Emirates", "Dubai"],
      ["Canada", "Toronto"],
      ["South Africa", "Cape Town"],
      ["India", "Mumbai"],
      ["China", "Shanghai"],
      ["Morocco", "Casablanca"],
      ["Nigeria", "Lagos"],
      ["Switzerland", "Zurich"],
    ],
    timezones: [
      ["United Kingdom", "UTC+0 in winter"],
      ["Denmark", "UTC+1 in winter"],
      ["United States", "UTC-5 to UTC-10"],
      ["India", "UTC+5:30"],
      ["China", "UTC+8"],
      ["Japan", "UTC+9"],
      ["Australia", "UTC+8 to UTC+10"],
      ["Brazil", "UTC-2 to UTC-5"],
      ["South Africa", "UTC+2"],
      ["United Arab Emirates", "UTC+4"],
      ["Argentina", "UTC-3"],
      ["New Zealand", "UTC+12"],
    ],
    carBrands: [
      ["Germany", "Volkswagen"],
      ["Japan", "Toyota"],
      ["United States", "Tesla"],
      ["Italy", "Ferrari"],
      ["South Korea", "Hyundai"],
      ["France", "Renault"],
      ["Sweden", "Volvo"],
      ["United Kingdom", "Rolls-Royce"],
      ["Czechia", "Skoda"],
      ["India", "Tata Motors"],
      ["China", "BYD"],
      ["Romania", "Dacia"],
    ],
    companies: [
      ["Denmark", "LEGO"],
      ["United States", "Apple"],
      ["South Korea", "Samsung"],
      ["Japan", "Nintendo"],
      ["Germany", "Siemens"],
      ["Switzerland", "Nestle"],
      ["Finland", "Nokia"],
      ["Sweden", "IKEA"],
      ["Netherlands", "ASML"],
      ["France", "LVMH"],
      ["China", "Alibaba"],
      ["India", "Infosys"],
    ],
    climates: [
      ["Egypt", "hot desert climate"],
      ["Brazil", "tropical rainforest climate in the Amazon"],
      ["Canada", "subarctic climate across much of the north"],
      ["Norway", "subarctic and oceanic climates"],
      ["Indonesia", "tropical rainforest climate"],
      ["Mongolia", "cold semi-arid steppe climate"],
      ["Spain", "Mediterranean climate"],
      ["Russia", "humid continental and subarctic climates"],
      ["Kenya", "tropical savanna climate"],
      ["Chile", "one of the world's driest desert climates"],
    ],
    tourism: [
      ["France", "one of the world's most visited countries"],
      ["Spain", "a top global beach and city tourism destination"],
      ["Thailand", "a major Southeast Asian tourism hub"],
      ["Mexico", "famous for Cancun and ancient ruins tourism"],
      ["Greece", "famous for island and ancient heritage tourism"],
      ["Turkey", "a major crossroads tourism destination"],
      ["Italy", "a top destination for art, food, and Roman history"],
      ["United Arab Emirates", "famous for luxury tourism in Dubai"],
      ["Egypt", "famous for pyramid and Nile tourism"],
      ["Japan", "known for city, temple, and cherry blossom tourism"],
    ],
    independence: [
      ["United States", "1776"],
      ["India", "1947"],
      ["Brazil", "1822"],
      ["Mexico", "1810"],
      ["Indonesia", "1945"],
      ["Finland", "1917"],
      ["Norway", "1905"],
      ["Ghana", "1957"],
      ["Kenya", "1963"],
      ["Algeria", "1962"],
      ["Ukraine", "1991"],
      ["South Sudan", "2011"],
    ],
    landscapes: [
      ["Egypt", "Nile River"],
      ["Brazil", "Amazon River"],
      ["United States", "Grand Canyon"],
      ["Norway", "Geirangerfjord"],
      ["Chile", "Atacama Desert"],
      ["Nepal", "Mount Everest"],
      ["Australia", "Great Barrier Reef"],
      ["Argentina", "Patagonia"],
      ["South Africa", "Cape of Good Hope"],
      ["Turkey", "Anatolian Peninsula"],
      ["India", "Ganges River"],
      ["Iceland", "Vatnajokull glacier"],
    ],
    mountains: [
      ["Japan", "Mount Fuji"],
      ["Tanzania", "Mount Kilimanjaro"],
      ["Switzerland", "the Matterhorn"],
      ["Argentina", "Aconcagua"],
      ["United States", "Denali"],
      ["Russia", "Mount Elbrus"],
      ["Indonesia", "Mount Bromo"],
      ["New Zealand", "Aoraki / Mount Cook"],
    ],
    rivers: [
      ["Egypt", "the Nile"],
      ["Brazil", "the Amazon"],
      ["China", "the Yangtze"],
      ["India", "the Ganges"],
      ["United States", "the Mississippi"],
      ["Germany", "the Rhine"],
      ["DR Congo", "the Congo River"],
      ["Vietnam", "the Mekong"],
    ],
    nationalParks: [
      ["United States", "Yellowstone National Park"],
      ["Tanzania", "Serengeti National Park"],
      ["Canada", "Banff National Park"],
      ["Croatia", "Plitvice Lakes National Park"],
      ["South Africa", "Kruger National Park"],
      ["Chile", "Torres del Paine National Park"],
      ["Australia", "Kakadu National Park"],
      ["Nepal", "Sagarmatha National Park"],
    ],
  };

  const languageChallenges = [
    { language: "Spanish", family: "Romance", region: "Europe and the Americas", continent: "Europe", sentence: "El mundo esta lleno de lugares sorprendentes." },
    { language: "French", family: "Romance", region: "Europe, Africa and Canada", continent: "Europe", sentence: "Le monde est rempli de lieux surprenants." },
    { language: "German", family: "Germanic", region: "Central Europe", continent: "Europe", sentence: "Die Welt ist voller erstaunlicher Orte." },
    { language: "Danish", family: "Germanic", region: "Northern Europe", continent: "Europe", sentence: "Verden er fuld af overraskende steder." },
    { language: "Swedish", family: "Germanic", region: "Northern Europe", continent: "Europe", sentence: "Varlden ar full av fantastiska platser." },
    { language: "Italian", family: "Romance", region: "Southern Europe", continent: "Europe", sentence: "Il mondo e pieno di luoghi sorprendenti." },
    { language: "Portuguese", family: "Romance", region: "Europe and South America", continent: "South America", sentence: "O mundo esta cheio de lugares surpreendentes." },
    { language: "Dutch", family: "Germanic", region: "Western Europe", continent: "Europe", sentence: "De wereld zit vol verrassende plekken." },
    { language: "Polish", family: "Slavic", region: "Central Europe", continent: "Europe", sentence: "Swiat jest pelen niezwyklych miejsc." },
    { language: "Czech", family: "Slavic", region: "Central Europe", continent: "Europe", sentence: "Svet je plny uzasnych mist." },
    { language: "Finnish", family: "Uralic", region: "Northern Europe", continent: "Europe", sentence: "Maailma on taynna ihmeellisia paikkoja." },
    { language: "Hungarian", family: "Uralic", region: "Central Europe", continent: "Europe", sentence: "A vilag tele van csodalatos helyekkel." },
    { language: "Greek", family: "Hellenic", region: "Southern Europe", continent: "Europe", sentence: "O kosmos einai gematos ekpliktika meri." },
    { language: "Romanian", family: "Romance", region: "Eastern Europe", continent: "Europe", sentence: "Lumea este plina de locuri uimitoare." },
    { language: "Turkish", family: "Turkic", region: "Anatolia", continent: "Asia", sentence: "Dunya sasirtici yerlerle doludur." },
    { language: "Indonesian", family: "Austronesian", region: "Southeast Asia", continent: "Asia", sentence: "Dunia penuh dengan tempat-tempat menakjubkan." },
    { language: "Vietnamese", family: "Austroasiatic", region: "Southeast Asia", continent: "Asia", sentence: "The gioi co rat nhieu noi tuyet voi." },
    { language: "Japanese", family: "Japonic", region: "East Asia", continent: "Asia", sentence: "Sekai wa odoroki no basho de afurete imasu." },
    { language: "Korean", family: "Koreanic", region: "East Asia", continent: "Asia", sentence: "Sesangeun nollaun gosdeullo gadeukhamnida." },
    { language: "Hindi", family: "Indo-Aryan", region: "South Asia", continent: "Asia", sentence: "Duniya adbhut jagahon se bhari hui hai." },
    { language: "Arabic", family: "Semitic", region: "Middle East and North Africa", continent: "Asia", sentence: "Al-alam مليء bil-amakin al-mudhila." },
    { language: "Persian", family: "Iranian", region: "Western Asia", continent: "Asia", sentence: "Jahan por az makan-haye shegeft-angiz ast." },
    { language: "Thai", family: "Kra-Dai", region: "Southeast Asia", continent: "Asia", sentence: "Lok tem pai duai sathanthi thi na pralat chai." },
    { language: "Swahili", family: "Bantu", region: "East Africa", continent: "Africa", sentence: "Dunia imejaa maeneo ya kushangaza." },
    { language: "Afrikaans", family: "Germanic", region: "Southern Africa", continent: "Africa", sentence: "Die wereld is vol wonderlike plekke." },
    { language: "Amharic", family: "Semitic", region: "East Africa", continent: "Africa", sentence: "Alem betam yemigeremu botawoch temtoal." },
    { language: "Yoruba", family: "Volta-Niger", region: "West Africa", continent: "Africa", sentence: "Aye kun fun awon ibi iyanu." },
    { language: "Zulu", family: "Bantu", region: "Southern Africa", continent: "Africa", sentence: "Umhlaba ugcwele izindawo ezimangalisayo." },
    { language: "Quechua", family: "Quechuan", region: "Andean South America", continent: "South America", sentence: "Kay pacha sumaq kitikunawan hunt'a kashan." },
    { language: "Guarani", family: "Tupian", region: "South America", continent: "South America", sentence: "Yvy henyhe tenda pora ha hechapyrava rehe." },
    { language: "Haitian Creole", family: "French Creole", region: "Caribbean", continent: "North America", sentence: "Mond lan plen ak kote etonan." },
    { language: "Navajo", family: "Athabaskan", region: "North America", continent: "North America", sentence: "Nahasdzáán nidaalnishgo bee ahoot'i'." },
    { language: "Maori", family: "Austronesian", region: "New Zealand", continent: "Oceania", sentence: "Ki tonu te ao i nga wahi whakamiharo." },
    { language: "Samoan", family: "Austronesian", region: "Polynesia", continent: "Oceania", sentence: "Ua tumu le lalolagi i nofoaga ofoofogia." },
  ];

  const landmarkData = [
    ["Eiffel Tower", 48.8584, 2.2945, "Paris, France", "Eiffel_Tower,_Paris_5_August_2014.jpg", "Built for the 1889 World's Fair, it was once criticized by many prominent Parisian artists."],
    ["Great Pyramid of Giza", 29.9792, 31.1342, "Giza, Egypt", "Kheops-Pyramid.jpg", "The oldest of the Seven Wonders of the Ancient World is also the only one still largely intact."],
    ["Statue of Liberty", 40.6892, -74.0445, "New York, United States", "Statue_of_Liberty_7.jpg", "France gifted the copper statue to the United States in the nineteenth century."],
    ["Machu Picchu", -13.1631, -72.545, "Peru", "Machu_Picchu,_Peru.jpg", "This fifteenth-century Inca citadel sits about 2,430 meters above sea level."],
    ["Sydney Opera House", -33.8568, 151.2153, "Sydney, Australia", "Sydney_Opera_House_Sails.jpg", "Its roof is formed from sections of the same enormous imaginary sphere."],
    ["Taj Mahal", 27.1751, 78.0421, "Agra, India", "Taj_Mahal,_Agra,_India_edit3.jpg", "The marble mausoleum was commissioned by Mughal emperor Shah Jahan."],
    ["Christ the Redeemer", -22.9519, -43.2105, "Rio de Janeiro, Brazil", "Cristo_Redentor_-_Rio_de_Janeiro,_Brasil.jpg", "The Art Deco statue stands on the summit of Corcovado mountain."],
    ["Mount Everest", 27.9881, 86.925, "Nepal-China border", "Mount_Everest_as_seen_from_Drukair2_PLW_edit.jpg", "Earth's highest point above sea level rises along the Nepal-China border."],
    ["Grand Canyon", 36.1069, -112.1129, "Arizona, United States", "Grand_Canyon_view_from_Pima_Point_2010.jpg", "The Colorado River exposed rock layers spanning nearly two billion years."],
    ["Angkor Wat", 13.4125, 103.867, "Cambodia", "Angkor_Wat.jpg", "Originally a Hindu temple, it gradually became an important Buddhist site."],
    ["Petra", 30.3285, 35.4444, "Jordan", "The_Treasury,_Petra,_Jordan.jpg", "The Nabataean city is famous for monumental buildings carved into rose-colored rock."],
    ["Burj Khalifa", 25.1972, 55.2744, "Dubai, United Arab Emirates", "Burj_Khalifa.jpg", "At 828 meters, it has been the world's tallest building since 2010."],
    ["Colosseum", 41.8902, 12.4922, "Rome, Italy", "Colosseum_in_Rome,_Italy_-_April_2007.jpg", "The Roman amphitheater could accommodate tens of thousands of spectators."],
    ["Great Wall of China", 40.4319, 116.5704, "China", "The_Great_Wall_of_China_at_Jinshanling-edit.jpg", "The wall is a network of fortifications built and rebuilt by several Chinese dynasties."],
    ["Moai of Rapa Nui", -27.125, -109.277, "Easter Island, Chile", "Moai_Rano_raraku.jpg", "Hundreds of monumental figures were carved by the Rapa Nui people from volcanic stone."],
    ["Chichen Itza", 20.6843, -88.5678, "Yucatan, Mexico", "Chichen_Itza_3.jpg", "El Castillo's stairways and terraces reflect Maya astronomical and calendrical knowledge."],
    ["Sagrada Familia", 41.4036, 2.1744, "Barcelona, Spain", "Sagrada_Familia_01.jpg", "Antoni Gaudi's basilica has been under construction since 1882."],
    ["Table Mountain", -33.9628, 18.4098, "Cape Town, South Africa", "Table_Mountain_DanieVDM.jpg", "Its flat summit overlooks Cape Town and supports unusually rich plant diversity."],
    ["Golden Gate Bridge", 37.8199, -122.4783, "San Francisco, United States", "Golden_Gate_Bridge_as_seen_from_Battery_East.jpg", "The suspension bridge spans the Golden Gate strait between San Francisco and Marin County."],
    ["CN Tower", 43.6426, -79.3871, "Toronto, Canada", "CN_Tower_2018.jpg", "The communications tower was the world's tallest free-standing structure for more than three decades."],
    ["Teotihuacan", 19.6925, -98.8438, "Mexico", "Teotihuacan,_Pyramid_of_the_Sun.jpg", "The ancient city contains the Pyramid of the Sun and the Avenue of the Dead."],
    ["Panama Canal", 9.08, -79.68, "Panama", "Panama_Canal_Gatun_Locks.jpg", "The canal connects the Atlantic and Pacific oceans through a system of locks and artificial lakes."],
    ["Brandenburg Gate", 52.5163, 13.3777, "Berlin, Germany", "Brandenburger_Tor_abends.jpg", "The eighteenth-century gate became a symbol of German division and reunification."],
    ["Acropolis of Athens", 37.9715, 23.7267, "Athens, Greece", "The_Parthenon_in_Athens.jpg", "The hilltop complex includes the Parthenon and other monuments of classical Athens."],
    ["Stonehenge", 51.1789, -1.8262, "Wiltshire, United Kingdom", "Stonehenge2007_07_30.jpg", "The prehistoric stone circle was constructed in several stages over many centuries."],
    ["Neuschwanstein Castle", 47.5576, 10.7498, "Bavaria, Germany", "Schloss_Neuschwanstein_2013.jpg", "King Ludwig II's nineteenth-century castle inspired later fairy-tale architecture."],
    ["Mount Fuji", 35.3606, 138.7274, "Japan", "Mt._Fuji_from_Mt._Ninoto.jpg", "Japan's highest mountain is an active stratovolcano and a major cultural symbol."],
    ["Forbidden City", 39.9163, 116.3972, "Beijing, China", "Forbidden_City_Beijing_Shenwumen_Gate.JPG", "The vast palace complex served as the imperial center of China for nearly five centuries."],
    ["Marina Bay Sands", 1.2834, 103.8607, "Singapore", "Marina_Bay_Sands_in_the_evening_-_20101120.jpg", "Three towers support a rooftop sky park overlooking Singapore's Marina Bay."],
    ["Borobudur", -7.6079, 110.2038, "Central Java, Indonesia", "Borobudur-Nothwest-view.jpg", "The ninth-century Buddhist monument is formed from stacked platforms covered with relief panels and stupas."],
    ["Ha Long Bay", 20.9101, 107.1839, "Vietnam", "Ha_Long_Bay_in_2019.jpg", "Thousands of limestone islands and pillars rise from the Gulf of Tonkin."],
    ["Serengeti National Park", -2.3333, 34.8333, "Tanzania", "Serengeti_Landscape.jpg", "The ecosystem is famous for its immense seasonal migration of wildebeest and zebra."],
    ["Victoria Falls", -17.9243, 25.8572, "Zambia-Zimbabwe border", "Victoria_Falls_2012.jpg", "The Zambezi River plunges across one of the world's widest continuous curtains of falling water."],
    ["Lalibela", 12.0317, 39.0476, "Ethiopia", "Bete_Giyorgis_03.jpg", "Its medieval churches were carved downward into volcanic rock."],
    ["Hassan II Mosque", 33.6084, -7.6326, "Casablanca, Morocco", "Hassan_II_Mosque_Casablanca.jpg", "The mosque's minaret rises above the Atlantic shoreline of Casablanca."],
    ["Uluru", -25.3444, 131.0369, "Northern Territory, Australia", "Uluru_Australia.jpg", "The sandstone monolith is sacred to the Anangu people and changes color dramatically with the light."],
    ["Milford Sound", -44.6716, 167.9256, "New Zealand", "Milford_Sound_02.jpg", "Steep glacially carved cliffs rise directly from the fjord in Fiordland."],
    ["Great Barrier Reef", -18.2871, 147.6992, "Australia", "Great_Barrier_Reef,_Australia.jpg", "The world's largest coral reef system stretches along Queensland's coast."],
    ["Torres del Paine", -51.0, -73.0, "Chile", "Torres_del_Paine_y_cuernos_del_Paine,_montaje.jpg", "Granite towers, glaciers, lakes, and steppe define this Patagonian national park."],
    ["Iguazu Falls", -25.6953, -54.4367, "Argentina-Brazil border", "Iguazu_Décembre_2007_-_Panorama_7.jpg", "Hundreds of cascades form a broad waterfall system on the Iguazu River."],
    ["Salar de Uyuni", -20.1338, -67.4891, "Bolivia", "Salar_de_Uyuni,_Bolivia.jpg", "The world's largest salt flat becomes a vast natural mirror during the wet season."],
    ["Galapagos Islands", -0.9538, -90.9656, "Ecuador", "Galapagos-satellite-2002.jpg", "The volcanic archipelago helped inspire Charles Darwin's ideas about evolution."],
    ["Geographic South Pole", -90, 0, "Antarctica", "Ceremonial_South_Pole.jpg", "The geographic pole marks Earth's southern rotational axis and is reached by every line of longitude."],
  ];

  const offlineUsdRates = {
    EUR: 1.08, GBP: 1.27, DKK: 0.145, SEK: 0.095, NOK: 0.094, CHF: 1.11, PLN: 0.25, CZK: 0.043,
    HUF: 0.00275, RON: 0.217, BGN: 0.552, ISK: 0.0072, TRY: 0.031, RUB: 0.011, UAH: 0.025,
    CAD: 0.73, MXN: 0.059, BRL: 0.20, ARS: 0.0011, CLP: 0.00105, COP: 0.00025, PEN: 0.27,
    CNY: 0.138, JPY: 0.0067, KRW: 0.00074, INR: 0.012, PKR: 0.0036, BDT: 0.0085, IDR: 0.000061,
    MYR: 0.212, THB: 0.028, VND: 0.000039, PHP: 0.017, SGD: 0.74, AUD: 0.66, NZD: 0.61,
    ZAR: 0.055, EGP: 0.020, MAD: 0.10, AED: 0.2723, SAR: 0.2667, ILS: 0.27, JOD: 1.41,
    KWD: 3.25, QAR: 0.2747, NGN: 0.00065, KES: 0.0077, GHS: 0.064, ETB: 0.008,
    XOF: 0.00165, XAF: 0.00165, XCD: 0.37, USD: 1,
  };

  const majorWaterLabels = [
    { name: "Atlantic Ocean", lat: 7, lon: -35, area: "106.5 million km²", info: "The Atlantic is the world's second-largest ocean and separates the Americas from Europe and Africa." },
    { name: "Pacific Ocean", lat: 2, lon: -145, area: "165.3 million km²", info: "The Pacific is Earth's largest and deepest ocean, covering more area than all land combined." },
    { name: "Indian Ocean", lat: -20, lon: 78, area: "70.6 million km²", info: "The Indian Ocean is the warmest major ocean and is strongly influenced by monsoon circulation." },
    { name: "Arctic Ocean", lat: 79, lon: 5, area: "14.1 million km²", info: "The Arctic is the smallest and shallowest major ocean and is seasonally covered by sea ice." },
    { name: "Southern Ocean", lat: -61, lon: 25, area: "20.3 million km²", info: "The Southern Ocean encircles Antarctica and drives the powerful Antarctic Circumpolar Current." },
  ];

  const minorWaterLabels = [
    { name: "Mediterranean Sea", lat: 35, lon: 18, info: "A nearly enclosed sea joining Europe, Africa, and Asia through the Strait of Gibraltar." },
    { name: "Caribbean Sea", lat: 15, lon: -75, info: "A tropical Atlantic sea bordered by the Antilles and the coasts of Central and South America." },
    { name: "Red Sea", lat: 20, lon: 38, info: "A narrow, warm sea between Africa and Arabia with extensive coral reefs." },
    { name: "Caspian Sea", lat: 41, lon: 51, info: "Despite its name, the Caspian is the world's largest enclosed inland body of water." },
    { name: "Black Sea", lat: 43, lon: 35, info: "A largely enclosed sea whose deep waters contain very little oxygen." },
    { name: "Baltic Sea", lat: 58, lon: 19, info: "A brackish northern European sea with limited exchange with the North Sea." },
    { name: "North Sea", lat: 56, lon: 3, info: "A shallow Atlantic sea important for shipping, fishing, energy, and offshore wind." },
    { name: "Great Lakes", lat: 45, lon: -84, info: "Five connected lakes containing about one-fifth of the world's surface fresh water." },
    { name: "Lake Victoria", lat: -1.1, lon: 33, info: "Africa's largest lake by area and the principal reservoir of the White Nile." },
    { name: "Lake Baikal", lat: 53.5, lon: 108, info: "The world's deepest lake and largest freshwater lake by volume." },
  ];

  const api = Object.freeze({
    allowedCountryNames,
    triviaExtras,
    languageChallenges,
    landmarkData,
    offlineUsdRates,
    majorWaterLabels,
    minorWaterLabels,
  });

  if (globalScope) globalScope.GeoSphereContent = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})(typeof window !== "undefined" ? window : globalThis);
